services:
  lab:
    build:
      context: .
      dockerfile: containers/Dockerfile
    container_name: manipylator-lab
    entrypoint: jupyter lab --notebook-dir=/workspace --ip 0.0.0.0 --port 8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - .:/workspace
    ports:
      - '8888:8888'
    restart: "no"
