services:
  lab:
    # build:
    #   context: .
    #   dockerfile: containers/Dockerfile
    image: leogold/manipylator:lab-dagger
    container_name: manipylator-lab
    entrypoint: /bin/bash -c "umask 000 && jupyter lab --notebook-dir=/workspace --ip 0.0.0.0 --port 8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.allow_remote_access=True --ServerApp.disable_check_xsrf=True"
    environment:
      DISPLAY: $DISPLAY
      PYTHONPATH: /workspace
    volumes:
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - .:/workspace
    ports:
      - '8888:8888'
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

# Include the controller compose file
include:
  - path: ./containers/controller/compose.yaml
    profiles:
      - full
      - simulated
