services:
  mq:
    image: eclipse-mosquitto:2.0.20
    hostname: mq
    container_name: mq
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto:/etc/mosquitto
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  lab:
    # build:
    #   context: .
    #   dockerfile: containers/Dockerfile
    image: manipylator-lab
    container_name: manipylator-lab
    entrypoint: jupyter lab --notebook-dir=/workspace --ip 0.0.0.0 --port 8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - .:/workspace
    ports:
      - '8888:8888'
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
