# derived from prind
# https://github.com/mkuf/prind

## Service Definitions
services:

  ## Klippy Services
  ##
  klipper: &klipper
    image: mkuf/klipper:latest
    restart: unless-stopped
    privileged: true
    # logging:
    #   driver: none
    profiles:
      - full
    depends_on:
      init:
        condition: service_completed_successfully
    command: >
      -I printer_data/run/klipper.tty -a printer_data/run/klipper.sock printer_data/config/printer.cfg -l printer_data/logs/klippy.log
    volumes:
      - /dev:/dev
      - ./config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
    labels:
      org.prind.service: klipper

  ## Reconfigure Klipper service for simulavr
  klipper-simulated:
    <<: *klipper
    depends_on:
      init:
        condition: service_completed_successfully
      simulavr:
        condition: service_started
    profiles:
      - simulated
    command: >
      -I printer_data/run/klipper.tty -a printer_data/run/klipper.sock printer_data/config/printer-simulavr.cfg -l printer_data/logs/klippy.log

  ## WebApi
  ##
  moonraker: &moonraker
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    # privileged: true
    # logging:
    #   driver: none
    depends_on:
      init:
        condition: service_completed_successfully
      klipper:
        condition: service_started
      mq:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ./config:/opt/printer_data/config
    profiles:
      - full
    labels:
      org.prind.service: moonraker
      traefik.enable: true
      traefik.http.services.moonraker.loadbalancer.server.port: 7125
      traefik.http.routers.moonraker.rule: PathPrefix(`/websocket`) ||  PathPrefix(`/printer`) ||  PathPrefix(`/api`) ||  PathPrefix(`/access`) ||  PathPrefix(`/machine`) || PathPrefix(`/server`)
      traefik.http.routers.moonraker.entrypoints: web

  moonraker-simulated:
    <<: *moonraker
    depends_on:
      init:
        condition: service_completed_successfully
      klipper-simulated:
        condition: service_started
      mq:
        condition: service_started
      simulavr:
        condition: service_started
    # post_start:
    #   - command: |
    #       mv /usr/bin/systemctl /usr/bin/systemctl.orig
    #       echo "#!/bin/bash\nsudo systemctl.orig" > /usr/bin/systemctl
    #       chmod +x /usr/bin/systemctl
    #     user: root
    profiles:
      - simulated

  ## Frontend
  ##
  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:edge
    restart: unless-stopped
    profiles:
      - full
      - simulated
    labels:
      org.prind.service: mainsail
      traefik.enable: true
      traefik.http.services.mainsail.loadbalancer.server.port: 80
      traefik.http.routers.mainsail.rule: PathPrefix(`/`)
      traefik.http.routers.mainsail.entrypoints: web

  ## simulavr
  simulavr:
    image: simulavr
    restart: unless-stopped
    build:
      context: ./simulavr
      # target: build-simulavr
    privileged: true
    volumes:
      - /dev:/dev
      - run:/opt/printer_data/run
    profiles:
      - simulated
    labels:
      org.prind.service: simulavr

  ## Loadbalancer/Proxy
  traefik:
    image: traefik:v2.11
    command:
      - "--accesslog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    profiles:
      - full
      - simulated
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      org.prind.service: traefik

  mq:
    image: eclipse-mosquitto:2.0.20
    hostname: mq
    # container_name: mq
    restart: unless-stopped
    profiles:
      - full
      - simulated
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto:/etc/mosquitto
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  make:
    image: mkuf/klipper:latest-tools
    tty: true
    privileged: true
    # entrypoint: make
    command:
      - /bin/sh
      - -c
      - |
        make menuconfig
        make
    working_dir: /opt/klipper
    profiles:
      - firmware
    volumes:
      # - /dev:/dev
      - ./config/build.config:/opt/klipper/.config
      - ./out:/opt/klipper/out

  ## Config dir needs to be writable by uid/gid 1000
  ## This container sets the right permissions and exits
  init:
    image: busybox:latest
    command: chown -R 1000:1000 /prind/config
    volumes:
      - .:/prind
    labels:
      org.prind.service: init

volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  moonraker-db:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
